GET https://10.34.0.14/W-AccessAPI/v1/cardholders/1069724

####

PUT https://10.34.0.14/W-AccessAPI/v1/cardholders
Content-Type: "application/json"

{
  "CHID": 1156717,
  "CHType": 8,
  "FirstName": "VITOR ARRAIS DE LAVOR MONTEIRO",
  "LastName": null,
  "CompanyID": null,
  "VisitorCompany": null,
  "EMail": null,
  "CHState": 0,
  "GDPRSignatureDateTime": null,
  "IsValidGDPRSignature": false,
  "IsUndesirable": false,
  "IsUndesirableReason1": null,
  "IsUndesirableReason2": null,
  "PartitionID": 1,
  "LastModifOnLocality": 1,
  "LastModifDateTime": "2024-08-27T16:04:46.377",
  "LastModifBy": null,
  "CHStartValidityDateTime": "2024-08-21T00:00:00",
  "CHEndValidityDateTime": "2024-10-01T00:00:00",
  "CHDownloadRequired": null,
  "TraceCH": null,
  "Trace_AlmP": 1,
  "Trace_Act": null,
  "TrustedLogin": null,
  "DefFrontCardLayout": null,
  "DefBackCardLayout": null,
  "IdNumber": "6210543",
  "MaxTransits": null,
  "MaxMeals": null,
  "IgnoreTransitsCount": true,
  "IgnoreMealsCount": false,
  "IgnoreAntiPassback": false,
  "IgnoreZoneCount": false,
  "PIN": null,
  "RequiresEscort": false,
  "CanEscort": false,
  "CanReceiveVisits": true,
  "SubZoneID": null,
  "IgnoreRandomInspection": false,
  "CHFloor": null,
  "BdccState": 0,
  "BdccIgnore": false,
  "BdccCompanies": null,
  "IdNumberType": null,
  "DisableAutoReturnVisCard": false,
  "DisableAutoReturnTempCard": false,
  "AuxText01": null,
  "AuxText02": null,
  "AuxText03": null,
  "AuxText04": "6210547397",
  "AuxText05": null,
  "AuxText06": null,
  "AuxText07": null,
  "AuxText08": null,
  "AuxText09": null,
  "AuxText10": null,
  "AuxText11": null,
  "AuxText12": null,
  "AuxText13": null,
  "AuxText14": null,
  "AuxText15": null,
  "AuxTextA01": null,
  "AuxTextA02": null,
  "AuxTextA03": null,
  "AuxTextA04": null,
  "AuxTextA05": null,
  "AuxLst01": null,
  "AuxLst02": 16,
  "AuxLst03": null,
  "AuxLst04": null,
  "AuxLst05": null,
  "AuxLst06": null,
  "AuxLst07": null,
  "AuxLst08": null,
  "AuxLst09": null,
  "AuxLst10": null,
  "AuxLst11": null,
  "AuxLst12": null,
  "AuxLst13": null,
  "AuxLst14": null,
  "AuxLst15": null,
  "AuxChk01": false,
  "AuxChk02": false,
  "AuxChk03": false,
  "AuxChk04": false,
  "AuxChk05": false,
  "AuxChk06": false,
  "AuxChk07": false,
  "AuxChk08": false,
  "AuxChk09": false,
  "AuxChk10": false,
  "AuxDte01": null,
  "AuxDte02": "2024-08-21T00:00:00",
  "AuxDte03": "2024-10-01T00:00:00",
  "AuxDte04": null,
  "AuxDte05": null,
  "AuxDte06": null,
  "AuxDte07": null,
  "AuxDte08": null,
  "AuxDte09": null,
  "AuxDte10": "2024-08-27T13:04:46.377",
  "Cards": [],
  "Groups": [],
  "CHAccessLevels": [],
  "PreAuthorizedVisits": [],
  "LastVisit": null,
  "ActiveVisit": null,
  "LastTransit": null
}